name: Build and Publish

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      pull-requests: write
    uses: unbounded-tech/workflows-containers/.github/workflows/publish.yaml@main
    with:
      tag_sha: true
